### ISSUE TITLE
Logging Not Enabled After Deployment

### ISSUE THREAD

**Issue by caa-build** [tjanczuk/iisnode#213]
I'm unable to access logging at http://mysite/iisnode/index.html after deploying my app. I receive a 404 accessing index.html or even iisnode/.

I am overriding the web.config file with iisnode.yml

Here's the yml file's contents:

``` yml
node_env: development
nodeProcessCountPerApplication: 1
maxConcurrentRequestsPerProcess: 1024
maxNamedPipeConnectionRetry: 24
namedPipeConnectionRetryDelay: 250
maxNamedPipeConnectionPoolSize: 512
maxNamedPipePooledConnectionAge: 30000
asyncCompletionThreadCount: 0
initialRequestBufferSize: 4096
maxRequestBufferSize: 65536
watchedFiles: *.js;iisnode.yml
uncFileChangesPollingInterval: 5000
gracefulShutdownTimeout: 60000
loggingEnabled: true
logDirectory: iisnode
debuggingEnabled: true
debuggerPortRange: 5058-6058
debuggerPathSegment: debug
maxLogFileSizeInKB: 128
maxTotalLogFileSizeInKB: 1024
maxLogFiles: 20
devErrorsEnabled: true
flushResponse: false
enableXFF: false
```

For good measure, here's the web.config file's contents:

``` xml
<?xml version="1.0" encoding="utf-8"?>
    <configuration>
        <system.webServer>
            <modules runAllManagedModulesForAllRequests="false" />
            <iisnode configOverrides="iisnode.yml" debuggingEnabled="true"  loggingEnabled="true" logDirectory="iisnode" devErrorsEnabled="true" nodeProcessCommandLine="&quot;%programfiles(x86)%\nodejs\node.exe&quot;"  />
            <handlers>
                <add name="iisnode" path="server.js" verb="*" modules="iisnode" />
            </handlers>
            <rewrite>
                <rules>
                    <clear />
                    <rule name="app" enabled="true" patternSyntax="ECMAScript" stopProcessing="true">
                        <match url="server\.js.+" negate="true" />
                        <conditions logicalGrouping="MatchAll" trackAllCaptures="false" />
                        <action type="Rewrite" url="server.js" />
                    </rule>
                    <rule name="LogFile" patternSyntax="ECMAScript" stopProcessing="true">
                        <match url="iisnode"/>
                    </rule>
                    <rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">
                        <match url="^server.js\/debug[\/]?" />
                    </rule>
                    <rule name="StaticContent">
                        <action type="Rewrite" url="public{{REQUEST_URI}}"/>
                    </rule>
                    <rule name="DynamicContent">
                        <conditions>
                            <add input="{{REQUEST_FILENAME}}" matchType="IsFile" negate="True"/>
                        </conditions>
                        <action type="Rewrite" url="server.js"/>
                    </rule>
                </rules>
            </rewrite>
        </system.webServer>
    </configuration>
```
